### ISSUE TITLE
ValueError: Unable to load configuration file: readfp() got an unexpected keyword argument 'source'

### ISSUE THREAD

**Issue by lfkwtz** [jdowner/gist#86]
running the unit test mentioned in the readme fails, as does running `gist list`

```
pi@chickenpotpi:~ $ sudo pip install python-gist
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: python-gist in /usr/local/lib/python2.7/dist-packages (0.9.2)
Requirement already satisfied: docopt in /usr/local/lib/python2.7/dist-packages (from python-gist) (0.6.2)
Requirement already satisfied: python-gnupg>=0.4.1 in /usr/local/lib/python2.7/dist-packages (from python-gist) (0.4.6)
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from python-gist) (2.24.0)
Requirement already satisfied: simplejson in /usr/local/lib/python2.7/dist-packages (from python-gist) (3.17.2)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->python-gist) (1.25.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->python-gist) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->python-gist) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->python-gist) (2.10)
pi@chickenpotpi:~ $ ls
chickenpotpi  gist
pi@chickenpotpi:~ $ cd gist/
pi@chickenpotpi:~/gist $ python setup.py test
running test
running egg_info
writing requirements to python_gist.egg-info/requires.txt
writing python_gist.egg-info/PKG-INFO
writing top-level names to python_gist.egg-info/top_level.txt
writing dependency_links to python_gist.egg-info/dependency_links.txt
writing entry points to python_gist.egg-info/entry_points.txt
reading manifest file 'python_gist.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'python_gist.egg-info/SOURCES.txt'
running build_ext
tests.test_gist (unittest.loader.ModuleImportFailure) ... ERROR

======================================================================
ERROR: tests.test_gist (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_gist
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/pi/gist/tests/test_gist.py", line 26, in <module>
    import responses
ImportError: No module named responses


----------------------------------------------------------------------
Ran 1 test in 0.007s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
pi@chickenpotpi:~/gist $ cd ..
pi@chickenpotpi:~ $ gist list
Traceback (most recent call last):
  File "/usr/local/bin/gist", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/gist/client.py", line 388, in main
    raise ValueError(message)
ValueError: Unable to load configuration file: readfp() got an unexpected keyword argument 'source'
```

**Comment by rtfmoz2** [comment]
The config.read_file(fp) on line 388 is only valid for configparser in Python 3. Upgrade to 3.7/3.8.

**Comment by veo-jdowner** [comment]
Thanks for responding to this @rtfmoz2, and apologies to @lfkwtz for letting this slip off the radar. Gist only supports versions 3.5, 3.6, and 3.7. It probably works with 3.8 but I need to test that to confirm.

**Comment by jdowner** [comment]
Thanks for responding to this @rtfmoz2, and apologies to @lfkwtz for letting this slip off the radar. Gist only supports versions 3.5, 3.6, and 3.7. It probably works with 3.8 but I need to test that to confirm.

**Comment by rtfmoz2** [comment]
Updated readme python3 requirement is known @lfkwtz
